-- OrderKar: add ingredients column + fill demo data. Safe to run any time.
alter table public.menu_items add column if not exists ingredients text;

update public.menu_items set ingredients = 'Chicken tikka, beef seekh kebab, malai boti, grilled wings, yoghurt, ajwain, garam masala, lemon' where name = 'BBQ Platter (Serves 2)';
update public.menu_items set ingredients = 'Beef, basmati rice, yoghurt, tomatoes, fried onions, biryani masala, saffron, mint' where name = 'Beef Biryani';
update public.menu_items set ingredients = 'Smashed beef patty, cheddar cheese, brioche bun, lettuce, tomato, burger sauce' where name = 'Beef Smash Burger';
update public.menu_items set ingredients = 'Beef strips, mustard oil, poppy seeds, yoghurt, behari masala, green chillies' where name = 'Behari Boti';
update public.menu_items set ingredients = 'Refined flour, mozzarella cheese, butter, yeast, salt' where name = 'Cheese Naan';
update public.menu_items set ingredients = 'Chicken, basmati rice, yoghurt, tomatoes, fried onions, biryani masala, green chillies' where name = 'Chicken Biryani';
update public.menu_items set ingredients = 'Egg noodles, chicken strips, cabbage, carrots, capsicum, soy sauce, garlic' where name = 'Chicken Chow Mein';
update public.menu_items set ingredients = 'Basmati rice, chicken, egg, spring onion, carrots, soy sauce' where name = 'Chicken Fried Rice';
update public.menu_items set ingredients = 'Chicken, tomatoes, julienned ginger, green chillies, black pepper, desi ghee' where name = 'Chicken Karahi (Full)';
update public.menu_items set ingredients = 'Chicken, tomatoes, julienned ginger, green chillies, black pepper, desi ghee' where name = 'Chicken Karahi (Half)';
update public.menu_items set ingredients = 'Chicken cubes, capsicum, garlic, ginger, soy sauce, egg-fried rice' where name = 'Chicken Manchurian with Rice';
update public.menu_items set ingredients = 'Chicken, basmati rice, yoghurt, cumin, black cardamom, whole spices' where name = 'Chicken Pulao';
update public.menu_items set ingredients = 'Marinated chicken strips, pita bread, garlic sauce, pickles, fries' where name = 'Chicken Shawarma';
update public.menu_items set ingredients = 'Chicken leg quarter, yoghurt, red chilli, ajwain, lemon, mustard oil' where name = 'Chicken Tikka';
update public.menu_items set ingredients = 'Chicken, seasoned flour coating, spices, deep-fried in oil' where name = 'Crispy Broast (2 pc)';
update public.menu_items set ingredients = 'Moong and chana daal, garlic tarka, cumin seeds, red chilli, desi ghee' where name = 'Daal Fry';
update public.menu_items set ingredients = 'Full-cream milk, strong patti tea leaves, sugar' where name = 'Doodh Patti';
update public.menu_items set ingredients = 'Fresh lime juice, soda water, mint leaves, salt, sugar' where name = 'Fresh Lime Soda';
update public.menu_items set ingredients = 'Refined flour, garlic, butter, fresh coriander, yeast' where name = 'Garlic Naan';
update public.menu_items set ingredients = 'Chicken wings, tikka marinade, red chilli, lemon, charcoal-grilled' where name = 'Grilled Wings (8 pc)';
update public.menu_items set ingredients = 'Khoya, refined flour, sugar syrup, green cardamom, rose water' where name = 'Gulab Jamun (4 pc)';
update public.menu_items set ingredients = 'Chicken strips, mushrooms, bamboo shoot, vinegar, white pepper, egg ribbons' where name = 'Hot & Sour Soup';
update public.menu_items set ingredients = 'Green tea leaves, milk, salt, crushed almonds and pistachios, rose petals' where name = 'Kashmiri Chai';
update public.menu_items set ingredients = 'Rice, full-cream milk, sugar, green cardamom, pistachios' where name = 'Kheer';
update public.menu_items set ingredients = 'Dense kulfi, vermicelli, rose syrup, basil seeds, chopped nuts' where name = 'Kulfi Falooda';
update public.menu_items set ingredients = 'Chicken cubes, roasted peanuts, dried red chillies, soy sauce, vinegar' where name = 'Kung Pao Chicken';
update public.menu_items set ingredients = 'Chicken cubes, fresh cream, cheese, white pepper, green chillies' where name = 'Malai Boti';
update public.menu_items set ingredients = 'Ripe mangoes, chilled milk, sugar, ice' where name = 'Mango Shake';
update public.menu_items set ingredients = 'Mutton, tomatoes, julienned ginger, green chillies, black pepper, desi ghee' where name = 'Mutton Karahi (Half)';
update public.menu_items set ingredients = 'Spinach, paneer cubes, garlic, fresh cream, garam masala' where name = 'Palak Paneer';
update public.menu_items set ingredients = 'Refined flour, sesame seeds, milk, yeast, salt' where name = 'Roghni Naan';
update public.menu_items set ingredients = 'Hand-minced beef, green chillies, fresh coriander, garam masala' where name = 'Seekh Kebab (4 pc)';
update public.menu_items set ingredients = 'Fried bread slices, rabri, sugar syrup, almonds, pistachios, cardamom' where name = 'Shahi Tukray';
update public.menu_items set ingredients = 'Whole wheat flour, water, salt, baked in clay tandoor' where name = 'Tandoori Roti (2 pc)';
update public.menu_items set ingredients = 'Basmati rice, cumin seeds, desi ghee, salt' where name = 'Zeera Rice';
update public.menu_items set ingredients = 'Crispy fried chicken fillet, sesame bun, mayonnaise, lettuce' where name = 'Zinger Burger';
